name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 15 3 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt install build-essential libsnmp-dev
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make
